### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by iancward** [rothgar/mastering-zsh#5]
Without using oh-my-zsh or another framework, what's the recommend way to install zsh?

I'm digging through stuff online and http://zsh.sourceforge.net and can't seem to find a recommended way to install it. 
Should I rely on my OS distro's available pacakge(s) to install it? Maybe I'm just become so accustomed to those crazy `curl | sudo bash` directions seemingly everywhere that installing things from OS packages has become a bit foreign 😆

**Comment by rothgar** [comment]
I've never installed zsh any other way besides distro packages. Some linux distros include it installed by default.
There might be better options if your distro has a really old version but the oldest I typically see is on RHEL or macOS and it's still >5.x

**Comment by iancward** [comment]
Ok that worked for me!
